### PR TITLE
Update libs, gradle and refactor code

### PR DESCRIPTION
**Pull request by cathirv**

### CODE REVIEW

**Comment by mukeshthawani** [comment]
Thanks for the PR @cathirv. Ashish(@reytum) will review it and update you.

**Comment by cathirv** [comment]
@mukeshthawani I need force a push to change agent's email address (build.gradle --> line 14), commit mine by mistake :( I have change made and squashed, but I can't force it

**Comment by mukeshthawani** [comment]
@cathirv I can see you have updated the email address so, I hope there is no issue now.

**Comment by cathirv** [comment]
I close PR because I have divided it into next three:
#7, #8 y #9

**Pull request closed without merging**
